# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Santa Tracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Santa Tracker
    pod 'RealmSwift', '2.1.0'


  target 'Santa TrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Santa TrackerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
